### ISSUE TITLE
Найти возможные варианты 2D движков

### ISSUE THREAD

**Issue by c58** [zombie-away/browser-game#1]
### The Problem
Найти список 2D движков для браузеров. Постараться найти плюсы и минусы у каждого, чтобы сделать объективный выбор.

### The Tasks
- [ ] По мере нахождения и анализа движков прикреплять комменты к ишью. Один для движка.

**Comment by MozalovPavel** [comment]
Движок pixi.js. Видел много советов использовать его.
+ Прикольные демки) 
+ Пишут, что достаточно классная вещь, 2D аналог three.js. 
+ Много звезд и форков на гитхабе)
+ поддержка WebGL
https://habrahabr.ru/post/174603/

**Comment by MozalovPavel** [comment]
Сначала сформирую список вариантов. Потом буду накидывать плюсы и минусы.

**Comment by MozalovPavel** [comment]
Cocos2d-js.

**Comment by MozalovPavel** [comment]
phaser.
https://github.com/photonstorm/phaser

**Comment by MozalovPavel** [comment]
Две хорошие ссылки на рейтинги.
https://github.com/showcases/javascript-game-engines
https://html5gameengine.com/

**Comment by MozalovPavel** [comment]
EaselJS.
https://github.com/CreateJS/EaselJS
http://createjs.com/

**Comment by c58** [comment]
Остановились на https://github.com/photonstorm/phaser
