### ISSUE TITLE
Планы по разработке.

### ISSUE THREAD

**Issue by MozalovPavel** [zombie-away/browser-game#2]
1. Примерно проиграть в голове сценарий игры (Что мы уже сделали. Есть примеры (Крэш бэндикут))
2. Архитектура приложения.
3. Самый простой прототип
    3.1 Сначала добавить фон и главного героя, научить его бегать.
    3.2 Создать карту, миссию и т.п.
    3.3 Создать первый прототип оружия
    3.4 Создать зомби
4. Добавить монетки и приколюхи (патроны, аптечки и т.п.)
5. Поработать с картой (Добавить препятствия)
6. Добавить еще одну миссию и питстоп для покупки оружия, патронов и аптечек
7. Проработать главного героя
    7.1 Добавить правильное поведение персонажа при вращении
    7.2 Добавить правильное поведение оружия и пуль при вращении
8. Хорошая отрисовка зомби, героя и карт.
9. Думаю еще много всякого)

**Comment by c58** [comment]
1. Для облегчения задачи стоит не примерно в голове, а четко и текстом описать один простой сценарий какого-то первого уровня и потом разбить его реализацию на части, от простого к сложному. Будет совсем круто если удастся нарисовать на бумаге некоторые кадры из игры, может быть со схемой движения (стрелочками показать кто куда и зачем двигается). Опять же потом прилепим к диплому эти зарисовки.
2. Здесь я думаю не нужно изобретать велосипед, я взять готовый боилерплейт (что ты скорее всего и сделал). Запустить его и запушить в эту репу
3. Вот этот план из 3 пункта должен вытекать из текста и бумажного прототипа, построенного на первом шаге. Я бы для начала сделал всю механику, без множества карт и миссиий, а уже потом добавлял вот это все. То есть сначала, например, нарисовать карту из прототипа, потом разместить на ней героя (кружок), потом научить его бегать со смещением камеры, потом стрелять из пистолета, потом добавить одного врага, потом много врагов...
4. В шаге 3 должен получиться прототип, который был придуман в шаге 1. В основном это вся механика движения персонажа, врагов, камеры, базового оружия. Дальше уже можно придумывать и миссии, и монетки и что угодно :)
